import type { Metadata } from "next";
import { Comfortaa,  Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import UserContextProvider from "@/provider/CurrentUser";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});



const comfortaa= Comfortaa({
  subsets: ["latin","cyrillic","cyrillic-ext"],
  weight: ["400", "500", "700"], // you can adjust weights if needed
});

export const metadata: Metadata = {
  title: "SixtySeconds",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${comfortaa.className} antialiased`}>
        <UserContextProvider>{children}</UserContextProvider>
      </body>
    </html>
  );
}
